# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-gitversion
  include:
  - dobi.yaml
  - version.yaml
  - gitversion/dobi.yaml

# ===================================================
# alias
# ===================================================

alias=version:
  tasks:
  - bb-gitversion-version
  annotations:
    description: "[alias] bb-gitversion-version"

alias=build:
  tasks:
  - bb-gitversion-build
  annotations:
    description: "[alias] bb-gitversion-build"
  
alias=deploy:
  tasks:
  - bb-gitversion-deploy
  annotations:
    description: "[alias] bb-gitversion-deploy"
  
alias=test: 
  tasks:
  - bb-gitversion-test
  annotations: 
    description: "[alias] bb-gitversion-test"
