# ===================================================
# meta infos
# ===================================================

meta:
  project: bb-gitversion
  include:
  - dobi.yaml
  - version.yaml
  - gitversion/dobi.yaml
