---
# General stuff
# -------------
## Specifies the name of the building block
bb_name: bb-example
## Specifies the destination of the docker image artifact
# Using docker hosts ip address for local environment
bb_destination: 172.17.0.1:5000/elbb/bb-example
## Specifies insecure docker registries, format "host:port" or "ip:port"
# Using docker hosts ip address for local environment
bb_destination_insecure_registries: ["172.17.0.1:5000"]

# Versioning stuff
# ----------------
## Specifies the version used for bb-gitversion
bb_gitversion_version: 0.3.0

# Git relevant stuff
# ------------------
## Specify the git repository to work with
git_source: https://github.com/elbb/bb-example.git
## Specify the git branch to work with
git_branch: example
## This enables/disables ssl verification of the git resource
git_skip_ssl_verification: false

# S3 relevant stuff
# -----------------
## Specify the S3 endpoint URI
# Using docker hosts ip address for local environment when using min.io locally
s3_endpoint: http://172.17.0.1:9000
## This enables/disables the ssl verification for the S3 endpoint
s3_skip_ssl_verification: true
