resources:
  - name: source
    type: git
    source:
      uri: ((git_source))
      private_key: ((privatekey))
      branch: ((git_branch))
      skip_ssl_verification: ((git_skip_ssl_verification))
      # This enables triggering on tag changes that match the glob pattern
      # tag_filter: "*"

  - name: bb-gitversion
    type: docker-image
    source:
      repository: elbb/bb-gitversion
      tag: ci

  - name: S3-gitversion
    type: s3
    source:
      bucket: ((name))
      endpoint: ((s3_endpoint))
      # at least one regex capture group is needed here
      regexp: version/(gitversion).tar.gz
      access_key_id: ((s3_access_key))
      secret_access_key: ((s3_secret_key))
      disable_ssl: ((s3_disable_ssl))

  - name: image-((name))
    type: docker-image
    source:
      repository: ((destination))
      tag: latest

jobs:
  - name: Generate gitversion and put it on S3
    public: true
    plan:
      - in_parallel:
          - get: bb-gitversion
          - get: source
      - task: Generate version
        image: bb-gitversion
        config:
          platform: linux
          inputs:
            - name: source
          outputs:
            - name: gen
          run:
            path: /bin/bash
            args:
              - -exc
              - |
                entrypoint.sh && 
                cat gen/json/gitversion.json && 
                tar cvfz gen/gitversion.tar.gz gen/*
          params:
            GIT_PATH: source
            GEN_PATH: gen
      - put: s3-gitversion
        params:
          file: gen/gitversion.tar.gz
          acl: public-read

  - name: Create docker image for ((name)) and push it
    public: true
    plan:
      - in_parallel:
          - get: source
          - get: s3-gitversion
            params:
              unpack: true
      - put: image-((name))
        params:
          build: source/docker
          dockerfile: source/docker/Dockerfile
          additional_tags: S3-gitversion/plain/SemVer
          tag_as_latest: true
